client_config_backend: settings

client_config:
  client_id: 314009165656-cfmo7ja4ocmqgpkspr2p5h2rdqeov9im.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
