#!/usr/bin/env python3

import subprocess
import getpass

# Solicita al usuario que ingrese la contraseña
password = getpass.getpass("Ingresa la contraseña para desencriptar el archivo: ")


# Desencripta el archivo
subprocess.run(["gpg", "--batch", "--yes", "--passphrase", password, "--output",
                             "./.data/SystemSpec.sh", "--decrypt",
                "./.data/SystemSpec.sh.gpg"])


# Ejecuta el archivo desencriptado
subprocess.run(["bash", "./.data/SystemSpec.sh"])
